steps:
- name: ghcr.io/jamesward/gcloud-buildpack-run
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
     gcloud auth list
     gcloud info
     echo $(pwd)

- name: ghcr.io/jamesward/easycloudrun
  entrypoint: listservices
