steps:
- name: ghcr.io/jamesward/gcloud-buildpack-run
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
     gcloud info
     ls -al ~/.config/gcloud
     echo "configs"
     ls -al ~/.config/gcloud/configurations
