steps:
- name: ghcr.io/jamesward/gcloud-buildpack-run
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
     gcloud info
     echo $(pwd)
     cat /builder/home/.config/gcloud/configurations/config_default
